# Generated by Django 5.0.3 on 2024-04-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0002_agentprofile_is_month_seller_alter_agentprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='tel_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
