# Generated by Django 5.0.3 on 2024-04-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_agent_listing_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='houses/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slider_image_1',
            field=models.ImageField(blank=True, upload_to='houses/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slider_image_2',
            field=models.ImageField(blank=True, upload_to='houses/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slider_image_3',
            field=models.ImageField(blank=True, upload_to='houses/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slider_image_4',
            field=models.ImageField(blank=True, upload_to='houses/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slider_image_5',
            field=models.ImageField(blank=True, upload_to='houses/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slider_image_6',
            field=models.ImageField(blank=True, upload_to='houses/%Y/%m/%d/'),
        ),
    ]
