# Generated by Django 5.0.3 on 2024-04-04 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acount', '0003_agentprofile_tel_num'),
        ('listings', '0004_listing_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_date', models.DateField(auto_now_add=True)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('is_viewed', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acount.customerprofile')),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.listing')),
            ],
        ),
    ]
